# Generated by Django 2.0.8 on 2018-08-19 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('currency', models.CharField(choices=[('JPY', 'JPY'), ('USD', 'USD')], max_length=5, verbose_name='currency')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='price')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='item.Item', verbose_name='item')),
            ],
        ),
    ]
